### ISSUE TITLE
No compiler source

### ISSUE THREAD

**Issue by alexoneill** [IanQS/stanford_compilers#1]
Does this compiler target Stanford students as input? Is it a collection of references to people who collect and collate information from Stanford?

Mode clarification would be good.

**Comment by IanQS** [comment]
Good question, @alexoneill. 

Re: no compiler source - The issue is that the class is 3 years old at this point and runs in 32 bits but my laptop does not. I chose to run it through their vm that they host on Bodhi Linux available on the site.

I think the end goal is to take in Stanford students as input but right now I'm having issues convincing them to let me upload them into my laptop - right now it just takes code. Do let me know if there are any more issues!
